### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by kvanla** [sillevl/node-teletask#1]
Tried to run this with my teletask micros+, however I kept getting parsing errors.
Parsing error: Parse error, wrong start byte (83,83,72,45,49,46,57,57,45,79,112,101,110,83,83,72,95,52,46,51,10)

**Comment by sillevl** [comment]
@kvanla are you sure you are connecting to the right port? By default this should be `55957` and the right host/ip? It seems your are trying to connect to an endpoint that serves SSH.

Check your configuration again

**Comment by sillevl** [comment]
@kvanla you might want to take a look at https://github.com/sillevl/teletask-mqtt as well. I understand you want to integrate it with Home Assistant (which I am doing with my setup).

The `sillevl/teletask-mqtt` application makes use of this library, and maps the Teletask functionality onto MQTT topics. This is easily integratable into Home Assistant using MQTT sensors and lights.
The `sillevl/teletask-mqtt` project is also available as a docker container for easy install and deployment (eg onto a Synology NAS)

**Comment by kvanla** [comment]
Thank you for reaching out to me so fast, 
![image](https://user-images.githubusercontent.com/85960686/123073580-d0a86d00-d416-11eb-88d1-064eb77c7b1d.png)
I tried the following script just to try it out, however the function doesn't return a value and when I analyse the packet stream with wireshark, It doesn't give me anything usefull. I think I have to use port 55955 since I have a micros plus ? using port 55957 just throws an error.
Is this because I don't have a tcp license ? Do you need one and if so do you know around how much this would cost and if it is a yearly payment or a one time thing ?

Yes I saw your other project after I made the issue, yesterday, I was planning on writing my own rest api but might use your mqtt project instead, had some difficulties setting up docker and using it on windows, so I switched to my ubuntu workplace, gonne experiment a bit more with it.

**Comment by sillevl** [comment]
You need a licence to open up the `55957` port for their `Open DOIP protocol`.

You can download a test licence (`TT15132-TEST MODE LICENTIE.act`) at https://professional.teletask.be/ . It enables you to test all functionalities for 24 hours. You can renew the licence in Prosoft as many times as you want, but requires some manual work. 

The download also provides information about the protocol they use to format the data, that is just send over the TCP sockets.

You will need to create an account in order to download it.

The Open DOIP protocol uses port `55957`, port `55955` is used by Prosoft.

**Comment by kvanla** [comment]
Thx for all the info, will check it out! All the licenses is a bit confusing and not much is said about it on the teletask website. Will check it out!

**Comment by sillevl** [comment]
Good luck, you can contact me if you need any help
